[project]
name = "pycon-25-hackathon"
version = "0.1.0"
description = "Intelligent Support Ticket Assignment System using LLMs"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "anthropic>=0.18.1",
    "pydantic>=2.6.0",
    "python-dotenv>=1.0.0",
    "rich>=13.7.0"
]
